import { Trip } from '../types';

export const mockTrips: Trip[] = [
  {
    id: '1',
    title: 'Icelandic Adventure',
    destination: 'Iceland',
    startDate: '2023-07-15',
    endDate: '2023-07-22',
    description: 'Explore the stunning landscapes of Iceland, from geysers to glaciers.',
    coverImageUrl: 'https://images.unsplash.com/photo-1529963183134-61a90db47eaf',
    travelAgency: 'Nordic Explorers',
    userId: 'user1',
    days: [
      {
        id: 'day1',
        date: '2023-07-15',
        activities: [
          {
            id: 'act1',
            title: 'Arrival and Hotel Check-in',
            description: 'Arrival at Keflavik International Airport and transfer to hotel in Reykjavik.',
            startTime: '14:00',
            endTime: '16:00',
            location: 'Reykjavik',
            includesTransportation: true,
            includesMeal: false,
          },
          {
            id: 'act2',
            title: 'Welcome Dinner',
            description: 'Group dinner at a traditional Icelandic restaurant.',
            startTime: '19:00',
            endTime: '21:00',
            location: 'Reykjavik Center',
            imageUrl: 'https://images.unsplash.com/photo-1533105079780-92b9be482077',
            includesTransportation: false,
            includesMeal: true,
            notes: 'Dress warmly, as the restaurant is near the harbor.',
          },
        ],
        notes: 'First day in Iceland! Rest well for tomorrow\'s adventures.',
      },
      {
        id: 'day2',
        date: '2023-07-16',
        activities: [
          {
            id: 'act3',
            title: 'Golden Circle Tour',
            description: 'Visit Thingvellir National Park, Geysir Hot Springs, and Gullfoss Waterfall.',
            startTime: '09:00',
            endTime: '17:00',
            location: 'Golden Circle',
            imageUrl: 'https://images.unsplash.com/photo-1523288864102-4a073b5c2b30',
            includesTransportation: true,
            includesMeal: true,
          },
          {
            id: 'act4',
            title: 'Northern Lights Hunting',
            description: 'Evening tour to spot the Aurora Borealis (weather permitting).',
            startTime: '21:00',
            endTime: '00:00',
            location: 'Outskirts of Reykjavik',
            includesTransportation: true,
            includesMeal: false,
            notes: 'Dress very warmly and bring a camera with tripod if possible.',
          },
        ],
      },
    ],
  },
  {
    id: '2',
    title: 'Tokyo Explorer',
    destination: 'Japan',
    startDate: '2023-09-10',
    endDate: '2023-09-17',
    description: 'Discover the vibrant city of Tokyo and its surrounding attractions.',
    coverImageUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26',
    travelAgency: 'Asia Journeys',
    userId: 'user1',
    days: [
      {
        id: 'day1',
        date: '2023-09-10',
        activities: [
          {
            id: 'act1',
            title: 'Arrival at Narita Airport',
            description: 'Arrival and transfer to hotel in Tokyo.',
            startTime: '13:00',
            endTime: '16:00',
            location: 'Tokyo',
            includesTransportation: true,
            includesMeal: false,
          },
          {
            id: 'act2',
            title: 'Shibuya Crossing Visit',
            description: 'Experience the famous Shibuya Crossing and surrounding area.',
            startTime: '18:00',
            endTime: '20:00',
            location: 'Shibuya, Tokyo',
            imageUrl: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989',
            includesTransportation: true,
            includesMeal: false,
          },
        ],
      },
    ],
  },
]; 